Name=input("Enter the name :")
Branch=input("Enter the branch :")
Gender=input("Enter the gender :")
College=input("Enter the college :")
Age=int(input("Enter the age :"))
print(Name)
print(Branch)
print(Gender)
print(College)
print(Age)
